services:
  web:
    container_name: web
    image: node:20.14-slim
    ports:
      - "4000:4000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm run start
  api:
    container_name: api
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api/app:/app
    working_dir: /app
  attack:
    container_name: attack
    image: node:20.14-slim
    ports:
      - "5000:4000"
    volumes:
      - ./attack:/app
    working_dir: /app
    command: npm run start
  private-api:
    container_name: private-api
    build: ./private-api
    volumes:
      - ./private-api/app:/app
    working_dir: /app
    expose:
      - 80
